name: Build test

on:
  pull_request:
    branches:
      - "17.0*"
  push:
    branches:
      - "17.0"

jobs:
  run-tests:
    uses: tawasta/github-workflows/.github/workflows/odoo-build-test.yml@main
    secrets: inherit